### ISSUE TITLE
зависимости

### ISSUE THREAD

**Issue by temnyuk** [ormorph/TDE#1]
А можно убрать зависимость tdewebdev у tde-base?
Или отдельным ключом. tdesdk не хочет собираться, мотивируя "cannot convert ‘TQCString’ to ‘DB_TXN*’". Но как-бы этот пакет не всем критичен.

**Comment by ormorph** [comment]
Убрать конечно можно, но хотелось бы разобраться со сборкой tdesdk.
1. Какую версию TDE собираете?
2. Перед сборкой размаскировали используя шаблон  **package.keywords/tde-14.0.***
3. Хотелось бы увидеть ваш **emerge --info**
Если версии пакетов соответствуют версиям tdebase, tdelibs, tqt, то как бы не должно быть проблем со сборкой. На всякий случай добавил флаг для компилятора, что бы использовал стандарт c++11 для сборки.

**Comment by temnyuk** [comment]
1. 14.0.6
2. Да, сделал симлинк
3. Portage 2.3.62 (python 2.7.16-final-0, default/linux/amd64/17.0/desktop, gcc-8.3.0, glibc-2.29-r1, 5.0.5-gentoo x86_64)
=================================================================
System uname: Linux-5.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i5-2400_CPU_@_3.10GHz-with-gentoo-2.6
KiB Mem:    16321272 total,  12025496 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Sun, 31 Mar 2019 16:30:01 +0000
Head commit of repository gentoo: 1c7389da1069aa72e36e6d53315f9bfbe94787c2
Head commit of repository 4nykey: d5a8ef08b33e4430d09a95ce4feefb50bc38635b

Head commit of repository TDE: 6ab49fc3c758873d4841d9f1cb71cf98976bd796

Head commit of repository mykrua: da53f67607ca0b46696b799e6975c3b7835ab87a

Head commit of repository tastytea: 35ca8d30634be9fb59aba1d64d9e943f06985d06

sh bash 5.0_p3-r1
ld GNU ld (Gentoo 2.32 p1) 2.32.0
app-shells/bash:          5.0_p3-r1::gentoo
dev-lang/perl:            5.28.0::gentoo
dev-lang/python:          2.7.16::gentoo, 3.6.8::gentoo
dev-util/cmake:           3.14.1::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.41.2::gentoo
sys-apps/sandbox:         2.17::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.32::gentoo
sys-devel/gcc:            8.3.0::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.0-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r1::gentoo
Repositories:

gentoo
    location: /home/gentoo/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: no
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24

4nykey
    location: /home/gentoo/4nykey
    sync-type: git
    sync-uri: https://github.com/4nykey/4nykey.git
    masters: gentoo

TDE
    location: /home/gentoo/TDE
    sync-type: git
    sync-uri: https://github.com/ormorph/TDE.git
    masters: gentoo

mykrua
    location: /home/gentoo/local
    sync-type: git
    sync-uri: ssh://git@my.kr.ua/gentoo-mykrua.git
    masters: gentoo

tastytea
    location: /home/gentoo/tastytea
    sync-type: git
    sync-uri: https://schlomp.space/tastytea/overlay.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/themes/oxygen-gtk/gtk-2.0"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.3/ext-active/ /etc/php/cgi-php7.3/ext-active/ /etc/php/cli-php7.3/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/home/gentoo/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="uk_UA.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="uk uk_UA"
MAKEOPTS="-j5"
PKGDIR="/home/gentoo/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac aacplus acl acpi aio alsa amd64 amr ao apulse berkdb branding bzip2 cairo calendar cli consolekit cxx dbus dri drm dts dvd dvdr emboss encode epub evdev exif faac flac fortran ftp gd gegl gif git glamor gmp gphoto2 gsm gstreamer iconv icu idn imlib ios jpeg kde kipi ladspa lame layers lcms libass libkms libmpv libnotify libtirpc libv4l linguas_uk logrotate lzo mad mclib minizip mng mount mp3 mp4 mpeg mtp multilib natspec ncurses nls nptl nsplugin nvidia ogg openal opengl openmp opus oscar osmesa pam pango pch pcre pdf phonon pim png policykit ppds qt4 quicktime rar readline sdl seccomp sftp smp sndfile sound spell ssh ssl startup-notification svg symlink sync-plugin-portage syslog taglib theora threads tiff truetype twolame udev udisks ukit unicode upower usb uvm uxa v4l vkd3d vorbis vpx vulkan wavpack webp x264 x265 x86emu xattr xcb xim xml xv xvid zip zlib" ABI_X86="64 32" ALSA_CARDS="hda-intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc" INPUT_DEVICES="evdev" KERNEL="linux" L10N="uk uk_UA" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" POSTGRES_TARGETS="postgres9_5 postgres10" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" QEMU_SOFTMMU_TARGETS="x86_64" QEMU_USER_TARGETS="x86_64" RUBY_TARGETS="ruby25" USERLAND="GNU" VIDEO_CARDS="nvidia v4l intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by ormorph** [comment]
Вы пытаетесь собрать на тестовой ветке, у меня данный оверлей собирался на стабильной с **gcc-8.2.0**.
Данная ошибка как правило может выскочить из за компилятора, но по идее добавление флага компилятору **-std=c++11** должно было решить эту проблему. После того как я изменил ебилд **trinity-base/tdesdk** и добавил флаг, вы не пробовали пере собирать tdesdk?
Пока добавил флаг webdev, в ебилд **tde-base-14.0.6**, по умолчанию он включен, остается его просто выключить.
По позже соберу **gcc-8.3.0** и проверю, повторится ли у меня эта ошибка.
А так для более точного вывода об ошибке, следует собрать с **MAKEOPTS="-j1"**

**Comment by ormorph** [comment]
Посмотрел, вы используете локальный оверлей, рекомендую использовать **layman**, для скачивания, как описано  https://unixforum.org/viewtopic.php?f=29&p=1324525#p1321079
Обновление  оверлея будет происходить на много проще:
**# layman -s TDE**

**Comment by ormorph** [comment]
Попробовал собрать gcc-8.3.0
tdesdk собралось норм, только не пробовал под последней версией cmake как у вас, может она генерирует отличный Makefile.
Можете собрать с **MAKEOPTS="-j1"** и показать вывод с ошибкой?
Возможно там варнинг на преобразование типов, а ошибка совершенно другая.
Можете попробовать использовать **wgetpaste** для вывода  текста с  ошибкой, что бы не засорять тут весть текст.

**Comment by temnyuk** [comment]
В стабильной ветке все нормально собирается, не собирается в тестовой. Вот вывод  с MAKEOPTS="-j1" https://pastebin.com/Jbm9vV1i

Еще к tdelibs нужно добавить зависимость berkdb у меня на одном компьютере не было, не захотел собираться пока не доставил сам.

**Comment by ormorph** [comment]
Добавил в зависимость **sys-libs/db** оно же berkdb.
У меня просто pam собран с флагом berkdb, по тому и не выскочило.
Кстати ошибка похоже выскакивает из за слишком новой версии **sys-libs/db**, Там что то поменяли вот и не идет. Как вариант можно попробовать замаскировать версии выше стабильной.
В tdesdk добавил генерацию Makefile c помощью ninja.
