### ISSUE TITLE
Fail build tde-style-baghira-9999 and trinity-apps/tde-style-domino-9999

### ISSUE THREAD

**Issue by dmxvlx** [ormorph/TDE#2]
Там ошибку выдаёт при сборке, в логе пишет что не может найти TQt:

> checking for TQt... configure: error: TQt (>= TQt 3.3 and < 4.0) (headers and libraries) not found. Please check your installation!

Собираю на виртбоксе, за основу взял **calculate linux scratch**.

В USE флагах пришлось убрать **jpeg2k** (пакет jasper не найден в портах).

собирал TDE, командой:

>  emerge tde-base

PS: спасибо огромное за проделанную работу ! кеды3 - просто супер ! (потом возможно попробую собрать и под raspberrypi 3/4)

PSS:  установлена dev-qt/tqt3-9999

**Comment by dmxvlx** [comment]
Ещё одна ошибка сборки подпакета tdefile-plugins/dependencies/poppler-tqt

> ninja: build stoppped: subcommand failed.
ERROR: trinity-base/tdegraphics-9999::TDE failed (compile phase):
  ninja -v -j5 -l0 failed

**Comment by dmxvlx** [comment]
в README.md нужно подправить строку с настройкой локализации,
привести к виду:

> L10N="de en"

**Comment by ormorph** [comment]
> Ещё одна ошибка сборки подпакета tdefile-plugins/dependencies/poppler-tqt
> 
> > ninja: build stoppped: subcommand failed.
> > ERROR: trinity-base/tdegraphics-9999::TDE failed (compile phase):
> > ninja -v -j5 -l0 failed

Тут вывод не полный.
Нужно содержимое файла:
**/var/tmp/portage/trinity-base/tdegraphics-9999/temp/build.log**
но это в Gentoo, в Calculate скорее всего это будет файл:
**/var/calculate/tmp/portage/trinity-base/tdegraphics-9999/temp/build.log**
Скорее всего причина в новом пакете **app-text/poppler**, у меня установлена версия **0.79.0-r1**, позже попробую обновиться.

**Comment by dmxvlx** [comment]
Уффф... Как не удобно (не привычно) по исходникам/логам лазить имея в наличии только **mc** и консоли (multimodal absence)... 

Сейчас накачу tde-base в основную систему, попробую поковырять билды, если взлетит - кину сюда изменения (или PR). На крайняк обеспечу полными логами ;)

**Comment by dmxvlx** [comment]
В данный момент переключился на версию tde-14.0.6.

Что имеем при сборке tde-style-baghira-14.0.6:

Не смотря на то, что параметр конфигурации для aRts не выставляется (./configure запускается с --without-arts), выдает такую ошибку:

> checking for mcopidl... not found
configure: error: The important program mcopidl was not found!
Please check whether you installed aRts correctly or use
--without-arts to compile without aRts support (this will remove functionality).

[полный лог файл](https://pastebin.com/SrjdZhMk)

Причина или в самом configure скрипте, или в конфигах *.in *.m4 (в которых я к сожалению ничего не смыслю).

Если вы имеете навыки с конфигурированием *.in *.m4 - исправьте плиз ))

**Comment by ormorph** [comment]
> В данный момент переключился на версию tde-14.0.6.
> 
> Что имеем при сборке tde-style-baghira-14.0.6:
> 
> Не смотря на то, что параметр конфигурации для aRts не выставляется (./configure запускается с --without-arts), выдает такую ошибку:
> 
> > checking for mcopidl... not found
> > configure: error: The important program mcopidl was not found!
> > Please check whether you installed aRts correctly or use
> > --without-arts to compile without aRts support (this will remove functionality).
> 
> [полный лог файл](https://pastebin.com/SrjdZhMk)
> 
> Причина или в самом configure скрипте, или в конфигах *.in *.m4 (в которых я к сожалению ничего не смыслю).
> 
> Если вы имеете навыки с конфигурированием *.in *.m4 - исправьте плиз ))

Хм, да там вроде в ебилде и тaк все прописано для сборки без arts.
Там перед **./configure** нужно прописать **build_arts=no**. Как то так:
`build_arts=no ./configure --without-arts ...`
Для тестирования сборки отдельного ебилда, не нужно переписывать команду в ручную. Для этого есть команда **ebuild**.
```
# cd /var/lib/layman/TDE/trinity-apps/tde-style-baghira
# ebuild tde-style-baghira-14.0.6.ebuild compile
```
Просмотреть все параметры для работы команды с ебилдом:
`# ebuild tde-style-baghira-14.0.6.ebuild help`
ps: перед выполнением compile нужно очистить каталог от предыдущей сборки:
`# ebuild tde-style-baghira-14.0.6.ebuild clean`

**Comment by dmxvlx** [comment]
Пакет **trinity-apps/tde-style-baghira** скомпилился !
Мне пришлось модифицировать билд, вернее одну ф-ию в нём
(добавлены строки с --with-qt-*):


```
src_configure() {
	unset TDE_FULL_SESSION TDEROOTHOME TDE_SESSION_UID TDEHOME TDE_MULTIHEAD
	export PKG_CONFIG_PATH=:/opt/trinity/lib/pkgconfig
	emake -f admin/Makefile.common
	build_arts=no ./configure --without-arts \
		--prefix="${TDEDIR}" \
		--exec-prefix="${TDEDIR}" \
		--datadir="${TDEDIR}/share" \
		--includedir="${TDEDIR}/include" \
		--libdir="${TDEDIR}/$(get_libdir)" \
		--with-qt-dir="${TDEDIR}" \
		--with-qt-includes="${TDEDIR}/include" \
		--with-qt-libraries="${TDEDIR}/$(get_libdir)" \
		--disable-dependency-tracking \
		--disable-debug \
		--enable-new-ldflags \
		--enable-final \
		--enable-closure \
		--enable-rpath \
		--disable-gcc-hidden-visibility || die
}
```


PS: возможно это нужно проделать и с другими пакетами __trinity-apps/tde-style-*__

**UPD**: подтверждаю: все билды __trinity-apps/tde-style-*__ нужно привести к такому же виду, добавив пути для Qt.

**UPD2**: билд trinity-apps/twin-style-crystal точно также изменить.

**Comment by ormorph** [comment]
> Мне пришлось модифицировать билд, вернее одну ф-ию в нём
> (добавлены строки с --with-qt-*):

Странно, у меня все собирается норм, без ошибок на tqt.
Возможно автоматом не подхватилась переменная.
Вроде это должно было правится командами:
```
# source /etc/profile
# env-update
```
либо перезагрузкой.
А так можно и подправить, что бы не выскакивало больше.

**Comment by dmxvlx** [comment]
> > Мне пришлось модифицировать билд, вернее одну ф-ию в нём
> > (добавлены строки с --with-qt-*):
> 
> Странно, у меня все собирается норм, без ошибок на tqt.
> Возможно автоматом не подхватилась переменная.
> Вроде это должно было правится командами:
> 
> ```
> # source /etc/profile
> # env-update
> ```
> 
> либо перезагрузкой.
> А так можно и подправить, что бы не выскакивало больше.

Да кстати, я об этом как-то не подумал...

**Comment by dmxvlx** [comment]
Пакет trinity-base/tdewebdev не устанавливается по той же самой причине, даже команда
> \# source /etc/profile && env-update

не помогла !

Ну в принципе мне не нужен этот пакет, да и не знаю я как там через CMAKE задаются пути к Qt ...

**Comment by ormorph** [comment]
> Пакет trinity-base/tdewebdev не устанавливается по той же самой причине, даже команда

Какую версию TDE собираете?

**Comment by dmxvlx** [comment]
собрал trinity-base/tde-base-**14.0.6**

++++++++++++++++++++++++++++++++++++++++++++

В /etc/init.d/xdm, в блок кода _case "${MY_XDM}" in_, нужно добавить вот это:

```
            tdm)
                        EXE=/opt/trinity/bin/tdm
                        PIDFILE=/run/tdm.pid
                        ;;
```

чтобы можно было указать в /etc/conf.d/xdm вот это:

```
DISPLAYMANAGER="tdm"
```

и наслаждаться графическим входом в систему...

**Comment by ormorph** [comment]
> чтобы можно было указать в /etc/conf.d/xdm вот это:

Похоже что все таки дело в переменной.
После установки tqt создаётся файл  **/etc/env.d/44tqt3**
Там прописывается переменная PATH. Т.е. данный файл не подхватывается.

**Comment by ormorph** [comment]
На счет команды:
`# source /etc/profile && env-update`
пардон, она не верная, надо наоборот выполнить:
`# env-update && source /etc/profile`

**Comment by dmxvlx** [comment]
Ok (когда-то, когда не было калькулейт, я тоже знал правильную последовательность этих двух команд :) )

**Comment by ormorph** [comment]
Мне в Calculate не нравится его ориентированность десктоп окружения на **consolekit**, в то время как уже существует другая альтернатива - **elogind**, там поддержка не включена в ядро, хотя этого не долго добиться. Без изменения конфига и пере сборки ядра в Calculate linux, нельзя добиться работоспособности **elogind**. Сам пакет есть, но он пустышка. Просто команды в elogind на много короче чем в consolekit, ну и сборку с гномом давно бы уже замутили, так как не привязан уже к systemd.
Так как я уже ранее пробовал делать Live cборки на основе calculate, то я уже натыкался на эти грабли, получалось все это довольно криво. Хотя все опции ядра для elogind давно уже указанны в wiki gentoo.
Хотя много подходов в calculate linux я нахожу довольно удобными.
TDE тоже может работать c elogind.

**Comment by dmxvlx** [comment]
Ну  у меня нет таких уж обширных знаний для настройки Gentoo (и других линуксов).
Просто раньше было время ознакомиться с этим прекрасным дистрибутивом, и по сей день умею немного вернуть к жизни поломавшуюся во время обновления систему (конфликты пакетов и другие прелести). В общем настраиваю окружение для разработки на с++.

К примеру сейчас: вчера скомпилил TDE, а вот запустить не получается - нужно настраивать xorg.conf и иже с ним - это про мои скилы настройки иксов и всё такое ))

**Comment by dmxvlx** [comment]
Посмотрел я TDENetworkManager - пичаль конечно, wifi соединение фиг разберёшь как настраивать :(

Не, я конечно осилю NetworkManager, и смогу настроить через консоль (или установить другой менеджер соединений, в два клика настраивающий wifi), но как-то не айс по сегодняшним меркам ...

По memory usage: я бы не сказал что TDE как-то существенно выигрывает, так как он отъедает 400МБ (с несколькими работающими приложениями), тот же современный KDE - 650.

В будущем буду попробовать под малинку4 (2ГБ RAM) собирать TDE.

**Comment by ormorph** [comment]
Ну NetworkManager, легче настроить через консольную **nmtui**, TDENetworkManager, тогда больше подойдёт для запуска уже настроенных соединений. А так **nm-applet**, так же хорошо работает и под TDE. 
На arm не тестировал, по этому как поведёт себя не знаю.

Есть возможность воспроизводить звук arts через pulseaudio, так как довольно много программ требуют его.
Собирается TDE с глобальным флагом **arts**, соответственно система с глобальным флагом pulseaudio.
Pulseaudio собирается с флагами **alsa alsa-plugin**.
Далее создается файлик .asoundrc, как [тут](https://unixforum.org/viewtopic.php?f=29&t=146242#p1324997). Далее нужно обеспечить запуск pulseaudio ранее TDE. Например можно прописать первой командой в скрипте **/opt/trinity/bin/starttde** первую команду:
`pulseaudio --start`
Тогда звуковая система автоматически будет стартовать через pulseaudio - alsa plugin. Звук единственное управлять будет удобнее через **pavucontrol**, но kmix будет работать с pulseaudio.

**Comment by dmxvlx** [comment]
OK ! спасибо !

**Comment by ormorph** [comment]
Нв счет ошибки в **tdegraphics**, то там причина в новом пакете poppler 0.82.
Проблема описана [тут](http://bugs.pearsoncomputing.net/show_bug.cgi?id=537#c5). 
Пока можно откатиться на более старую версию, либо собирать **tdegraphics** с выключенным флагом **-pdf** для данного пакета, только тогда не будет доступна программа **kpdf**.

**Comment by dmxvlx** [comment]
Именно так я и поступил, когда вы упомянули об установленной у вас версии poppler-0.79 ))
