### ISSUE TITLE
lm_sensors

### ISSUE THREAD

**Issue by mittorn** [ormorph/TDE#3]
It seems, it renamed to lm-sensors now, so deps are broken

**Comment by ormorph** [comment]
```
sensors? ( || ( sys-apps/lm_sensors
	sys-apps/lm-sensors ) )
```
Either `sys-apps/lm_sensors` or `sys-apps/lm-sensors` can be used.
Currently busy with the [tde-packaging-gentoo](https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo) overlay, so I haven't updated this overlay in a while. The `trinity-nomodules` branch is the most working so far.

**Comment by mittorn** [comment]
This does not work when lm-sensors masked, it shows only error about lm_sensors.
(It is masked on aarch64)

**Comment by ormorph** [comment]
Ok, fixed.
I recommend using version 14.0.9.

**Comment by mittorn** [comment]
It's too late, i already built 14.0.8, so only on next update
